# Generated by Django 5.1.3 on 2025-01-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('group', models.CharField(max_length=255)),
            ],
        ),
    ]
